server {
    listen 80;
    server_name localhost;
    client_max_body_size 25m;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location / {
        set $firespot_backend http://web:80;
        proxy_pass $firespot_backend;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
