<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require_once __DIR__.'/../app/partner_entitlements.php';

$checks=0;
$expect=static function(bool $condition,string $message)use(&$checks):void{$checks++;if(!$condition)throw new RuntimeException($message);};
$root=dirname(__DIR__);
$migration=(string)file_get_contents($root.'/migrations/051_partner_portal_governance.sql');
$subscriptionMigration=(string)file_get_contents($root.'/migrations/052_multipoint_subscription_v2.sql');
$ownershipMigration=(string)file_get_contents($root.'/migrations/053_partner_owned_nas_self_service.sql');
$smoke=(string)file_get_contents($root.'/migrations/smoke_051.php');
$entitlements=(string)file_get_contents($root.'/app/partner_entitlements.php');
$roles=(string)file_get_contents($root.'/app/partner_admin.php');
$domain=(string)file_get_contents($root.'/app/partner_infrastructure.php');
$central=(string)file_get_contents($root.'/app/control_center_partners.php');
$actions=(string)file_get_contents($root.'/portal/host/panel_actions.php');
$entry=(string)file_get_contents($root.'/portal/host/index.php');
$infrastructure=(string)file_get_contents($root.'/portal/host/pages/infrastructure.php');
$nasPage=(string)file_get_contents($root.'/portal/host/pages/nas.php');
$hotspotsPage=(string)file_get_contents($root.'/portal/host/pages/hotspots.php');
$portal=(string)file_get_contents($root.'/portal/host/pages/portal.php');
$portalIdentity=(string)file_get_contents($root.'/portal/host/pages/portal_identity.php');
$courtesyPage=(string)file_get_contents($root.'/portal/host/pages/courtesy.php');
$commercialDomain=(string)file_get_contents($root.'/app/partner_hotspot_commercial.php');
$commercialMigration=(string)file_get_contents($root.'/migrations/056_hotspot_commercial_policies.sql');
$hostJavascript=(string)file_get_contents($root.'/portal/host/assets/host-admin.js');
$simulator=(string)file_get_contents($root.'/simulador/index.php');
$preview=(string)file_get_contents($root.'/portal/host/portal_preview.php');
$shortPreview=(string)file_get_contents($root.'/admin/portal_preview.php');
$skin=(string)file_get_contents($root.'/app/portal_skin.php');
$deployCheck=(string)file_get_contents($root.'/app/cli/portal_skin_deploy_check.php');
$finalizer=(string)file_get_contents('/opt/firespot-ops/firespot_portal_v3_skins_finalize_root.sh');

foreach(['partner_nas_assignments','legacy_point','legacy_ownership','multipoint_advanced',"version=2",'portal.presentation.manage'] as $needle)$expect(str_contains($migration,$needle),'Migração 051 incompleta: '.$needle);
$expect(str_contains($subscriptionMigration,"event_type='plan_version_migrated'")&&str_contains($subscriptionMigration,"old_plan.version=1")&&str_contains($subscriptionMigration,"new_plan.version=2"),'Migração 052 não conclui a sucessão das assinaturas Multipontos vigentes.');
$expect(!str_contains($subscriptionMigration,'portal_mode')&&!str_contains($subscriptionMigration,'partner_hotspots')&&!str_contains($subscriptionMigration,'partner_nas'),'Migração 052 ultrapassa a fronteira comercial e pode alterar portal, ponto ou NAS.');
$expect(str_contains($migration,"max_nas,max_hotspots")&&str_contains($migration,"0,25,10,366,25"),'Plano Multipontos v2 ainda concede cota de NAS ou perdeu a cota de pontos.');
foreach(['nas.manage','nas.prepare','nas.retire','hotspots.apply'] as $feature)$expect(str_contains($migration,"SELECT '{$feature}'"),'Bloqueio versionado ausente: '.$feature);
$expect(str_contains($smoke,'Ponto existente sem atribuição contextual de NAS'),'Smoke não valida o backfill de atribuições.');
$expect(fs_partner_nas_self_service_allowed()===true,'Política não reconhece o NAS próprio contratado.');
foreach(['nas.manage','nas.prepare','nas.retire'] as $feature)$expect(!fs_partner_feature_is_central_only($feature),'Recurso de NAS próprio ainda está bloqueado antes da decisão do plano: '.$feature);
$expect(str_contains($roles,"'infrastructure.view','nas.manage','nas.prepare','nas.retire'"),'Proprietário e gerente não recebem capacidades de NAS próprio.');
$expect(!str_contains($roles,"'hotspots.manage','hotspots.apply'"),'Proprietário ainda recebe aplicação remota de pontos.');
$expect(str_contains($domain,'function fs_partner_nas_assert_assigned'),'Rascunho de ponto não exige NAS atribuído.');
$expect(str_contains($domain,'function fs_partner_hotspot_assert_draft_nas')&&substr_count($domain,'fs_partner_hotspot_assert_draft_nas($pdo,$partnerId,$nasId,true)')>=3,'Criação, edição e solicitação de mudança não revalidam propriedade ou atribuição do NAS conforme o plano.');
$expect(str_contains($domain,'$owned=fs_partner_nas_assert_owned($pdo,$partnerId,$nasId,false,$forUpdate)')&&str_contains($domain,"(\$owned['base_status']??'')!=='ready'"),'Plano com autogestão não restringe o rascunho a NAS próprio com base preparada.');
$expect(str_contains($central,'fs_partner_nas_assignment_ensure'),'A Central não registra a atribuição ao selecionar o NAS.');
$expect(str_contains($infrastructure,'name="action" value="nas_register"'),'Painel não expõe cadastro contratual de NAS próprio.');
$expect(str_contains($infrastructure,'name="action" value="nas_update"'),'Painel não permite definir ou atualizar credenciais protegidas do NAS próprio.');
$expect(str_contains($infrastructure,'name="action" value="nas_prepare"'),'Painel não expõe a preparação auditada do NAS próprio.');
$expect(str_contains($infrastructure,'name="action" value="nas_retire"'),'Painel não permite aposentadoria segura do NAS próprio.');
$expect(!str_contains($infrastructure,'name="action" value="hotspot_apply"'),'Painel expõe aplicação remota.');
$expect(str_contains($infrastructure,'hotspot_draft_create')&&str_contains($infrastructure,'hotspot_draft_update')&&str_contains($infrastructure,'hotspot_draft_discard'),'CRUD de rascunho de ponto incompleto.');
$expect(!str_contains($infrastructure,'credential_hint')&&!str_contains($infrastructure,'host_key_fingerprint'),'Painel tenta reexibir credencial ou chave SSH persistida.');
foreach(['fs_partner_nas_register(','fs_partner_nas_update_credentials(','fs_partner_nas_queue_operation(','fs_partner_nas_retire('] as $call)$expect(str_contains($actions,$call),'Controlador não encaminha a operação de NAS próprio: '.$call);
foreach(['fs_partner_hotspot_queue_apply(','fs_partner_hotspot_queue_deactivate('] as $call)$expect(!str_contains($actions,$call),'Controlador do estabelecimento executa aplicação remota de ponto: '.$call);
$expect(str_contains($actions,"in_array(\$action,['hotspot_apply','hotspot_deactivate'],true)"),'Controlador não rejeita explicitamente aplicação e retirada remota de pontos.');
$expect(str_contains($ownershipMigration,"equipment.shortname IN ('Demo-NAS-A','Demo-NAS-B')")&&str_contains($ownershipMigration,"partner.code='00000001'"),'Classificação dos dois NAS confirmados não está fechada ao example_partner.');
$expect(str_contains($ownershipMigration,"'hotspots.apply',0")&&str_contains($ownershipMigration,"'nas.manage',0")&&str_contains((string)file_get_contents($root.'/app/cli/adopt_example_partner_partner_nas.php'),"feature_code IN ('nas.manage','nas.prepare','nas.retire')"),'Adoção v3 libera capacidades antes da propriedade atômica ou confunde NAS com aplicação remota de ponto.');
$expect(str_contains($entry,"'portal' => ['theme.manage','portal','portal.presentation.manage']"),'Página do Portal V3 não exige papel, módulo e plano.');
$expect(str_contains($entry,"'nas' => ['infrastructure.view','infrastructure','nas.view']")&&str_contains($entry,"'hotspots' => ['infrastructure.view','infrastructure','hotspots.view']"),'NAS e Pontos Hotspot não possuem autorização independente na navegação.');
$expect(str_contains($entry,"'courtesy' => ['courtesy.view','portal','courtesy.view']")&&str_contains($entry,"['courtesy','Cortesia padrão','courtesy.view','portal','courtesy.view'"),'Padrão de cortesia desaparece quando a modalidade ainda não faz parte da jornada publicada.');
$expect(str_contains($infrastructure,'Acesso deste ponto')&&str_contains($infrastructure,'name="action" value="hotspot_commercial_save"')&&str_contains($infrastructure,'Cobrança por acesso')&&str_contains($infrastructure,'Janela temporária Pix'),'Janela do ponto não concentra as modalidades e regras comerciais independentes.');
$expect(!str_contains($entry,"'payment' =>")&&!str_contains($entry,"['payment','Pagamento Pix'")&&!is_file($root.'/portal/host/pages/payment.php'),'Política Pix continua duplicada em uma página global do estabelecimento.');
$expect(str_contains($actions,"'hotspot_commercial.manage','infrastructure','hotspots.draft.manage',true")&&str_contains($actions,"'hotspot.commercial_policy_updated'")&&str_contains($actions,'fs_partner_hotspot_commercial_save'),'Gravação das regras do ponto não revalida permissão, plano e auditoria.');
$expect(str_contains($commercialDomain,"management_mode='partner_owned'")&&str_contains($commercialDomain,"courtesy.hotspot_override.manage")&&str_contains($commercialDomain,"wallet.manage"),'Domínio comercial não restringe a mutação ao ponto próprio ou aos entitlements contratados.');
$expect(str_contains($commercialMigration,'O backfill copia o comportamento publicado atual')&&str_contains($commercialMigration,'partner_hotspot_commercial_policies'),'Migração comercial por ponto não preserva explicitamente o comportamento publicado.');
$expect(str_contains($courtesyPage,'Padrão de cortesia')&&str_contains($courtesyPage,'Configurar por ponto')&&!str_contains($courtesyPage,'Exceções por ponto'),'Cortesia mantém duas superfícies concorrentes para editar o mesmo ponto.');
$expect(str_contains($nasPage,"\$infrastructureView='nas'")&&str_contains($hotspotsPage,"\$infrastructureView='hotspots'")&&!str_contains($entry,"'Pontos e NAS'"),'A antiga página combinada ainda é canônica ou as páginas independentes não foram ligadas.');
$expect(str_contains($actions,"'portal.presentation.manage',true"),'Gravação visual não revalida o plano.');
$expect(str_contains($actions,"'partner_admin'")&&str_contains($skin,'fs_portal_presentation_actor_type'),'Autoria do estabelecimento não é registrada.');
$expect(str_contains($portal,'Um único motor de acesso')&&str_contains($portal,'cinco modelos visuais'),'Contrato de portal único não está explícito.');
$expect(!str_contains($entry,"['simulation','Simulação'")&&!str_contains($entry,"['theme','Identidade atual'")&&str_contains($entry,"in_array(\$page,['theme','simulation'],true)"),'Simulação e identidade ainda competem com a página unificada ou os favoritos antigos deixaram de ser compatíveis.');
$expect(str_contains($portal,"require __DIR__ . '/portal_identity.php'")&&str_contains($portalIdentity,'name="return_page" value="portal"'),'Editor visual preservado não foi incorporado à página única do Portal V3.');
$expect(str_contains($portal,'data-host-modal-open="host-modal-simulation"')&&str_contains($portal,'data-host-modal-open="host-modal-preview"')&&str_contains($hostJavascript,'data-host-modal-frame'),'Simulação e prévias não abrem nas janelas sobrepostas da página unificada.');
$expect(str_contains($simulator,'<?php if(!$embed):?><header')&&str_contains($simulator,'name="embed" value="1"'),'Simulador incorporado repete a navegação externa ou perde o modo incorporado ao trocar de ponto.');
$expect(str_contains($actions,'Identidade visual atualizada e incorporada ao rascunho V3')&&str_contains($actions,"fs_portal_presentation_get(\$pdo,\$partnerId,'draft')"),'Identidade única não é propagada ao rascunho V3 existente.');
$expect(str_contains($portal,'data-host-frame-src="<?=host_h($previewUrl)?>"')&&str_contains($portal,"'/admin/portal_preview.php?viewport='")&&str_contains($shortPreview,"../portal/host/portal_preview.php"),'Prévia modal do painel não usa uma entrada curta existente e estável.');
$expect(str_contains($skin,"mkdir(\$directory,02770,true)")&&str_contains($skin,'is_writable($directory)'),'Armazenamento das imagens não exige diretório privado gravável pelo grupo de serviço.');
$expect(str_contains($portal,'não publica o V3')&&str_contains($portal,'não altera NAS'),'Editor não informa seus limites de segurança.');
$expect(!str_contains($portal,'portal_activate')&&!str_contains($actions,'UPDATE partners SET portal_mode'),'Painel pode ativar o V3.');
$expect(str_contains($preview,"partner_admin_require_feature_context(\$pdo,'theme.manage','portal','portal.presentation.manage',false)"),'Prévia não isola estabelecimento, papel e plano.');
$expect(str_contains($preview,"'preview'=>true")&&str_contains($preview,"'preview_asset_base'=>'../../portal-v3/'"),'Prévia não usa o renderer único em modo seguro.');
$expect(!preg_match('/<script(?![^>]+\bsrc=)[^>]*>/i',$entry),'Painel mantém JavaScript executável inline.');
$expect(!preg_match('/\sstyle\s*=/i',$entry.$infrastructure.$portal),'Páginas principais mantêm estilo inline.');
$expect(str_contains($finalizer,'50,51,52')&&str_contains($finalizer,'v052'),'Finalizador não instala o prefixo 050-052 e seu baseline.');
$expect(str_contains($finalizer,'umask 077')&&str_contains($finalizer,'[[ -s ${backup_file} ]]'),'Backup do finalizador pode ficar temporariamente exposto ou vazio.');
$verifyPosition=strpos($finalizer,'"${runner}" --verify');$applyPosition=strpos($finalizer,'"${runner}" --apply');
$expect($verifyPosition!==false&&$applyPosition!==false&&$verifyPosition<$applyPosition,'Finalizador não valida os smokes instalados antes de alterar o schema.');
$expect(str_contains($finalizer,'/tests/*_test.php')&&is_file($root.'/tests/control_center_authenticated_render_test.php'),'Finalizador não repete a auditoria autenticada de renderização e acessibilidade.');
$expect(str_contains($finalizer,"-name '*.php' -print0")&&str_contains($finalizer,"-name '*.js' -print0")&&str_contains($finalizer,'/tests/*_test.php'),'Finalizador não cobre toda a sintaxe PHP/JavaScript e a regressão completa.');
$expect(str_contains($finalizer,'node_major >= 16')&&str_contains($finalizer,'node_binary')&&!str_contains($finalizer,'/usr/bin/node --check'),'Finalizador aceita o Node.js 12 incompatível com os assets modernos.');
$expect(str_contains($finalizer,"50,51,52) deployment_state='fresh'")&&str_contains($finalizer,"51,52) deployment_state='resume_051'")&&str_contains($finalizer,"52) deployment_state='resume_052'")&&str_contains($finalizer,"deployment_state='resume_post_schema'"),'Finalizador não pode retomar com segurança depois da 050, 051 ou dos testes pós-schema.');
$expect(str_contains($deployCheck,"'hotspot-digest'")&&str_contains($deployCheck,"'nas-assignment-digest'")&&str_contains($deployCheck,"'assert-multipoint-v2'"),'Verificador não expõe as provas finais de pontos, NAS e sucessão comercial.');
$expect(str_contains($finalizer,'hotspot_digest_before')&&str_contains($finalizer,'hotspot_digest_after')&&str_contains($finalizer,'nas_assignment_digest_before')&&str_contains($finalizer,'nas_assignment_digest_after'),'Finalizador não compara os pontos e as atribuições de NAS antes e depois da 052.');
$expect(str_contains($finalizer,'--assert-multipoint-v2'),'Finalizador não confirma o contrato Multipontos v2 depois da migração.');
foreach(['partner_nas_assignments','portal_skin_catalog','partner_portal_presentations','partner_portal_migrations'] as $table)$expect(str_contains($deployCheck,"'{$table}'"),'Backup retomável não inclui a tabela: '.$table);
$expect(str_contains($deployCheck,"'partner_subscription_events'"),'Backup retomável não preserva a auditoria da sucessão comercial.');
$expect(str_contains($deployCheck,'information_schema.TABLES')&&str_contains($finalizer,'${#backup_tables[@]} -gt 0'),'Seleção do backup não distingue tabelas ainda ausentes ou aceita lista vazia.');

echo 'OK: '.$checks." verificações de governança do painel e Portal V3.\n";
