<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
putenv('PERSONAL_DATA_KEY='.base64_encode(str_repeat('A',32)));
require_once __DIR__.'/../app/db.php';
require_once __DIR__.'/../app/subscriber_accounts.php';
require_once __DIR__.'/../app/subscriber_admin.php';
$checks=0;function subscriber_account_expect(bool $ok,string $message):void{global$checks;$checks++;if(!$ok)throw new RuntimeException($message);}
$pdo=db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$document='52998224725';$customerId='test-'.bin2hex(random_bytes(6));
$fetcher=static fn(string $doc):array=>[['id_cliente'=>$GLOBALS['customerId'],'nome'=>'Titular transacional','ativo'=>true,'telefone_primario'=>'(92) 99999-4321','servicos'=>[['id_servico'=>'svc-test','id_plano'=>'plan-unknown','tipo_servico'=>'Internet fibra','status'=>'Serviço Habilitado']]]];
$pdo->beginTransaction();
try{
    fs_subscriber_feature_set($pdo,'subscriber_access_enabled',true);fs_subscriber_feature_set($pdo,'subscriber_account_enabled',true);
    $sync=fs_subscriber_sync_document($pdo,$document,['fetcher'=>$fetcher]);subscriber_account_expect(!empty($sync['ok'])&&$sync['result_code']==='DEFAULT_BASIC_UNMAPPED','Cliente elegível sem mapeamento não recebeu perfil básico.');
    $accountId=(int)$sync['account']['id'];$ent=fs_subscriber_entitlement($pdo,$accountId);subscriber_account_expect($ent['profile_code']==='firenetwork_basic'&&$ent['status']==='active','Entitlement básico não foi persistido.');
    $snapshot=json_decode((string)$ent['source_snapshot'],true);subscriber_account_expect(!isset($snapshot['phone'])&&!isset($snapshot['email'])&&!isset($snapshot['document']),'Snapshot armazenou PII indevida.');
    $authenticator=static fn(string $username,string $password):array=>$password==='senha-valida-de-teste'?['status'=>200,'json'=>['status'=>'success','cliente'=>['id_cliente'=>$GLOBALS['customerId'],'cpf_cnpj'=>$username]]]:['status'=>401,'json'=>['status'=>'error']];
    $invalidPassword=false;try{fs_subscriber_login_password($pdo,$document,'senha-incorreta',false,['authenticator'=>$authenticator,'fetcher'=>$fetcher]);}catch(RuntimeException $e){$invalidPassword=$e->getMessage()==='CPF/CNPJ ou senha não conferem.';}subscriber_account_expect($invalidPassword,'Senha HubSoft inválida foi aceita ou revelou dados da conta.');
    $passwordLogin=fs_subscriber_login_password($pdo,$document,'senha-valida-de-teste',false,['authenticator'=>$authenticator,'fetcher'=>$fetcher]);subscriber_account_expect(!empty($passwordLogin['ok'])&&($passwordLogin['auth_method']??'')==='hubsoft_password'&&($_SESSION['subscriber_auth_method']??'')==='hubsoft_password','Senha válida do HubSoft não autenticou a Minha Conta.');
    $st=$pdo->prepare('SELECT outcome,result_code FROM subscriber_auth_attempts WHERE document_hash=? ORDER BY id DESC LIMIT 2');$st->execute([fs_subscriber_document_hash($document)]);$passwordAttempts=$st->fetchAll();subscriber_account_expect(($passwordAttempts[0]['outcome']??'')==='success'&&($passwordAttempts[1]['result_code']??'')==='INVALID_CREDENTIALS','Resultados da autenticação por senha não foram auditados corretamente.');
    $remoteBlocked=false;try{fs_subscriber_login_password($pdo,$document,'senha-de-teste',false,['authenticator'=>static fn(string $username,string $password):array=>['status'=>403,'json'=>['status'=>'error']],'fetcher'=>$fetcher]);}catch(RuntimeException $e){$remoteBlocked=str_contains($e->getMessage(),'bloqueou temporariamente');}subscriber_account_expect($remoteBlocked,'Bloqueio remoto do HubSoft foi apresentado como senha inválida ou indisponibilidade.');
    $st=$pdo->prepare('SELECT outcome,result_code FROM subscriber_auth_attempts WHERE document_hash=? ORDER BY id DESC LIMIT 1');$st->execute([fs_subscriber_document_hash($document)]);$remoteAttempt=$st->fetch();subscriber_account_expect(($remoteAttempt['outcome']??'')==='blocked'&&($remoteAttempt['result_code']??'')==='REMOTE_FORBIDDEN','Bloqueio remoto não foi auditado com código operacional.');
    $st=$pdo->query("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='subscriber_auth_attempts' AND COLUMN_NAME REGEXP 'password|senha|secret|payload'");subscriber_account_expect((int)$st->fetchColumn()===0,'Estrutura de tentativas permite persistir a senha do HubSoft.');
    for($i=0;$i<4;$i++){try{fs_subscriber_login_password($pdo,$document,'senha-incorreta',false,['authenticator'=>$authenticator,'fetcher'=>$fetcher]);}catch(RuntimeException $e){}}
    $rateLimited=false;try{fs_subscriber_login_password($pdo,$document,'senha-incorreta',false,['authenticator'=>$authenticator,'fetcher'=>$fetcher]);}catch(RuntimeException $e){$rateLimited=str_contains($e->getMessage(),'15 minutos');}subscriber_account_expect($rateLimited,'Limite de tentativas da senha HubSoft não foi aplicado.');
    $login=fs_subscriber_login_start($pdo,$document,['fetcher'=>$fetcher,'test_return_code'=>true]);subscriber_account_expect(preg_match('/^\d{6}$/',(string)$login['_test_code'])===1&&str_ends_with((string)$login['contact_hint'],'4321'),'OTP não foi destinado ao contato confirmado.');
    $st=$pdo->prepare("SELECT to_msisdn,msg,payload_encrypted FROM promo_queue WHERE purpose='subscriber_otp' AND reference_type='login_challenge' ORDER BY id DESC LIMIT 1");$st->execute();$queued=$st->fetch();subscriber_account_expect($queued['to_msisdn']==='ENCRYPTED'&&$queued['msg']==='ENCRYPTED'&&str_starts_with((string)$queued['payload_encrypted'],'pi1:'),'Fila expôs OTP ou destino em texto puro.');
    $wrongBlocked=false;try{fs_subscriber_login_verify($pdo,$login['challenge'],'000000',false);}catch(RuntimeException $e){$wrongBlocked=true;}subscriber_account_expect($wrongBlocked,'OTP incorreto foi aceito.');
    $verified=fs_subscriber_login_verify($pdo,$login['challenge'],$login['_test_code'],false);subscriber_account_expect(!empty($verified['ok'])&&(int)$verified['account']['id']===$accountId,'OTP correto não autenticou a conta esperada.');
    $reuseBlocked=false;try{fs_subscriber_login_verify($pdo,$login['challenge'],$login['_test_code'],false);}catch(RuntimeException $e){$reuseBlocked=true;}subscriber_account_expect($reuseBlocked,'OTP foi reutilizado.');
    $cached=fs_subscriber_sync_document($pdo,$document,['fetcher'=>static function(string $doc):array{throw new RuntimeException('offline');}]);subscriber_account_expect(!empty($cached['ok'])&&$cached['result_code']==='PROVIDER_UNAVAILABLE_CACHE'&&$cached['entitlement']['status']==='grace','Indisponibilidade do HubSoft não respeitou a tolerância ativa.');
    $mappingDocument='11144477735';$mappingService='svc-review-'.bin2hex(random_bytes(4));$mappingCustomer='review-'.bin2hex(random_bytes(5));
    $mappingFetcher=static fn(string $doc):array=>[['id_cliente'=>$GLOBALS['mappingCustomer'],'ativo'=>true,'telefone_primario'=>'(92) 98888-1122','servicos'=>[['id_servico'=>$GLOBALS['mappingService'],'nome_servico'=>'Serviço adicional','status'=>'Serviço Habilitado']]]];
    $mappingSync=fs_subscriber_sync_document($pdo,$mappingDocument,['fetcher'=>$mappingFetcher]);subscriber_account_expect(empty($mappingSync['ok'])&&$mappingSync['result_code']==='SERVICE_MAPPING_REQUIRED','Serviço ativo não reconhecido foi liberado sem confirmação ou recebeu diagnóstico genérico.');
    $mappingLogin=fs_subscriber_login_start($pdo,$mappingDocument,['fetcher'=>$mappingFetcher,'test_return_code'=>true]);$st=$pdo->prepare('SELECT account_id,queue_id FROM subscriber_login_challenges WHERE public_id=?');$st->execute([$mappingLogin['challenge']]);$mappingChallenge=$st->fetch();subscriber_account_expect(empty($mappingChallenge['account_id'])&&empty($mappingChallenge['queue_id']),'OTP foi enfileirado antes da confirmação do serviço elegível.');
    $unknown=fs_subscriber_admin_unknown_ids($pdo);$discovered=array_values(array_filter($unknown,static fn(array $item):bool=>$item['kind']==='service'&&$item['external_id']===$GLOBALS['mappingService']))[0]??[];subscriber_account_expect(($discovered['label']??'')==='Serviço adicional'&&empty($discovered['internet_detected']),'Painel não expôs o ID pendente com diagnóstico seguro.');
    fs_subscriber_account_anonymize($pdo,$accountId);$anonymized=fs_subscriber_account($pdo,$accountId);$st=$pdo->prepare('SELECT status,document_encrypted,verified_phone_encrypted FROM subscriber_external_links WHERE account_id=?');$st->execute([$accountId]);$link=$st->fetch();subscriber_account_expect($anonymized['status']==='anonymized'&&$anonymized['display_name']===null&&$link['status']==='revoked'&&$link['document_encrypted']===null&&$link['verified_phone_encrypted']===null,'Anonimização preservou identidade ou contato da conta.');
    $st=$pdo->prepare('SELECT COUNT(*) FROM subscriber_auth_attempts WHERE account_id=? OR document_hash=?');$st->execute([$accountId,fs_subscriber_document_hash($document)]);subscriber_account_expect((int)$st->fetchColumn()===0,'Anonimização preservou vínculo das tentativas de autenticação com o documento.');
    $renewed=fs_subscriber_sync_document($pdo,$document,['fetcher'=>$fetcher]);subscriber_account_expect(!empty($renewed['ok'])&&(int)$renewed['account']['id']!==$accountId,'Novo vínculo reutilizou uma conta anonimizada.');
    $pdo->rollBack();unset($_SESSION['subscriber_account_id'],$_SESSION['subscriber_session_version'],$_SESSION['subscriber_authenticated_at'],$_SESSION['subscriber_auth_method']);
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();unset($_SESSION['subscriber_account_id'],$_SESSION['subscriber_session_version'],$_SESSION['subscriber_authenticated_at'],$_SESSION['subscriber_auth_method']);throw$e;}
echo "OK: {$checks} verificações integradas de conta, OTP e tolerância HubSoft.\n";
