<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
putenv('PERSONAL_DATA_KEY='.base64_encode(str_repeat('D',32)));
require_once __DIR__.'/../app/db.php';
require_once __DIR__.'/../app/subscriber_radius.php';
require_once __DIR__.'/../app/partner_hotspots.php';
$checks=0;function subscriber_domain_expect(bool $ok,string $message):void{global$checks;$checks++;if(!$ok)throw new RuntimeException($message);}
$pdo=db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);
$hotspotId=(int)$pdo->query('SELECT h.id FROM partner_hotspots h JOIN partners p ON p.id=h.partner_id WHERE h.active=1 AND p.active=1 ORDER BY h.id LIMIT 1')->fetchColumn();
if($hotspotId<=0)throw new RuntimeException('Nenhuma instalação ativa para o teste.');
$partner=fs_partner_hotspot_by_id($pdo,$hotspotId,null,true);if(!$partner)throw new RuntimeException('Contexto da instalação não encontrado.');
$pdo->beginTransaction();
try{
    foreach(fs_subscriber_feature_labels() as $key=>$label)fs_subscriber_feature_set($pdo,$key,true);
    $profileCode='test_'.bin2hex(random_bytes(5));$st=$pdo->prepare('INSERT INTO subscriber_benefit_profiles (code,name,device_limit,concurrent_limit,revalidation_minutes,download_kbps,upload_kbps) VALUES (?,\'Perfil transacional\',2,1,30,8000,2000)');$st->execute([$profileCode]);$profileId=(int)$pdo->lastInsertId();
    $public=fs_subscriber_public_id();$documentHash=hash('sha256','subscriber-domain-'.$public);$st=$pdo->prepare("INSERT INTO subscriber_accounts (public_id,status,display_name,document_hash) VALUES (?,'active','Conta transacional',?)");$st->execute([$public,$documentHash]);$accountId=(int)$pdo->lastInsertId();
    $st=$pdo->prepare("INSERT INTO subscriber_entitlements (account_id,benefit_profile_id,provider,status,result_code,verified_at,valid_until,grace_until) VALUES (?,?,'hubsoft','active','TEST',NOW(),DATE_ADD(NOW(),INTERVAL 2 HOUR),DATE_ADD(NOW(),INTERVAL 1 DAY))");$st->execute([$accountId,$profileId]);
    $context=['partner_id'=>(int)$partner['id'],'hotspot_id'=>(int)$partner['hotspot_id'],'mac'=>'02:00:00:AA:10:01'];
    $primary=fs_subscriber_authorize_primary($pdo,$accountId,$context);subscriber_domain_expect((int)$primary['account_id']===$accountId&&$primary['device_kind']==='primary','Aparelho principal não foi autorizado.');
    $invite=fs_subscriber_invite_create($pdo,$accountId,['label'=>'Convidado transacional','authorization_mode'=>'temporary','access_duration_minutes'=>60,'invite_ttl_minutes'=>15]);subscriber_domain_expect(strlen($invite['token'])===48&&strlen($invite['code'])>=8,'Segredos do convite não foram criados no formato esperado.');
    $redeemed=fs_subscriber_invite_redeem($pdo,$invite['token'],['partner_id'=>(int)$partner['id'],'hotspot_id'=>(int)$partner['hotspot_id'],'mac'=>'02:00:00:AA:10:02']);$guest=$redeemed['device'];subscriber_domain_expect((int)$guest['id']>0,'Convite não criou aparelho convidado.');
    $reusedBlocked=false;try{fs_subscriber_invite_redeem($pdo,$invite['token'],$context);}catch(RuntimeException $e){$reusedBlocked=true;}subscriber_domain_expect($reusedBlocked,'Convite foi reutilizado.');
    $occupancy=fs_subscriber_device_occupancy($pdo,$accountId,true);subscriber_domain_expect($occupancy['used']===2&&$occupancy['available']===0,'Ocupação não respeitou as duas vagas.');
    $limitBlocked=false;try{fs_subscriber_invite_create($pdo,$accountId,['label'=>'Terceiro']);}catch(RuntimeException $e){$limitBlocked=true;}subscriber_domain_expect($limitBlocked,'Uma terceira vaga foi reservada acima do limite.');
    fs_subscriber_reconcile_devices($pdo,$accountId,true,1);$guestAfterDowngrade=fs_subscriber_device_by_id($pdo,(int)$guest['id']);subscriber_domain_expect($guestAfterDowngrade['status']==='over_limit','Downgrade não suspendeu o aparelho excedente.');
    fs_subscriber_reconcile_devices($pdo,$accountId,true,2);$guestAfterUpgrade=fs_subscriber_device_by_id($pdo,(int)$guest['id']);subscriber_domain_expect($guestAfterUpgrade['status']==='active','Upgrade não restaurou a autorização excedente.');
    $partner['_device_mac']='02:00:00:AA:10:01';$partner['_device_ip']='10.250.0.10';$grant=fs_subscriber_radius_reserve($pdo,$accountId,(int)$primary['id'],$partner,'first-request',$pdo);
    subscriber_domain_expect(!empty($grant['username'])&&!empty($grant['password'])&&$grant['grant']['status']==='active','Credencial RADIUS individual não foi provisionada.');
    $attrs=$pdo->prepare('SELECT attribute,value FROM radcheck WHERE username=?');$attrs->execute([$grant['username']]);$attrs=array_column($attrs->fetchAll(), 'value','attribute');subscriber_domain_expect(($attrs['Simultaneous-Use']??'')==='1'&&isset($attrs['Cleartext-Password'])&&isset($attrs['Calling-Station-Id']),'Atributos RADIUS obrigatórios estão incompletos.');
    $rate=$pdo->prepare("SELECT value FROM radreply WHERE username=? AND attribute='Mikrotik-Rate-Limit' LIMIT 1");$rate->execute([$grant['username']]);subscriber_domain_expect((string)$rate->fetchColumn()==='2000k/8000k','O limite padrão do perfil não foi enviado ao RADIUS na ordem upload/download do RouterOS.');
    $pdo->prepare('UPDATE subscriber_benefit_profiles SET download_kbps=9000,upload_kbps=2500 WHERE id=?')->execute([$profileId]);
    $reconnect=fs_subscriber_radius_reserve($pdo,$accountId,(int)$primary['id'],$partner,'second-request',$pdo);subscriber_domain_expect($reconnect['grant']['public_id']===$grant['grant']['public_id'],'Reconexão criou uma segunda concessão para o mesmo aparelho.');
    $rate->execute([$grant['username']]);subscriber_domain_expect((string)$rate->fetchColumn()==='2500k/9000k','A reconexão não reaplicou o limite atualizado do benefício.');
    $mappingExternalId='test-rate-'.$public;$st=$pdo->prepare("INSERT INTO subscriber_plan_mappings (provider,external_kind,external_id,external_label,eligible_internet,benefit_profile_id,download_kbps,upload_kbps,active) VALUES ('hubsoft','service',?,'Velocidade transacional',1,?,12000,4000,1)");$st->execute([$mappingExternalId,$profileId]);$mappingId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE subscriber_entitlements SET plan_mapping_id=? WHERE account_id=?')->execute([$mappingId,$accountId]);
    fs_subscriber_radius_prepare_reconnect($pdo,$grant['grant'],$pdo);$rate->execute([$grant['username']]);subscriber_domain_expect((string)$rate->fetchColumn()==='4000k/12000k','A velocidade do mapeamento não substituiu o limite padrão do perfil.');
    $victimPublic=fs_subscriber_public_id();$st=$pdo->prepare("INSERT INTO subscriber_accounts (public_id,status,display_name,document_hash) VALUES (?,'active','Outra conta transacional',?)");$st->execute([$victimPublic,hash('sha256','subscriber-domain-victim-'.$victimPublic)]);$victimAccountId=(int)$pdo->lastInsertId();
    $st=$pdo->prepare("INSERT INTO subscriber_entitlements (account_id,benefit_profile_id,provider,status,result_code,verified_at,valid_until,grace_until) VALUES (?,?,'hubsoft','active','TEST',NOW(),DATE_ADD(NOW(),INTERVAL 2 HOUR),DATE_ADD(NOW(),INTERVAL 1 DAY))");$st->execute([$victimAccountId,$profileId]);
    $victimDevice=fs_subscriber_authorize_primary($pdo,$victimAccountId,['partner_id'=>(int)$partner['id'],'hotspot_id'=>(int)$partner['hotspot_id'],'mac'=>'02:00:00:AA:10:03']);$partner['_device_mac']='02:00:00:AA:10:03';$victimGrant=fs_subscriber_radius_reserve($pdo,$victimAccountId,(int)$victimDevice['id'],$partner,'victim-request',$pdo);
    $crossAccountBlocked=false;try{fs_subscriber_device_revoke($pdo,$accountId,(int)$victimDevice['id']);}catch(RuntimeException $e){$crossAccountBlocked=true;}
    $st=$pdo->prepare('SELECT status FROM subscriber_access_grants WHERE id=?');$st->execute([(int)$victimGrant['grant']['id']]);$victimGrantStatus=(string)$st->fetchColumn();$st=$pdo->prepare('SELECT COUNT(*) FROM radcheck WHERE username=?');$st->execute([$victimGrant['username']]);
    subscriber_domain_expect($crossAccountBlocked&&$victimGrantStatus==='active'&&(int)$st->fetchColumn()>0,'Uma conta conseguiu revogar a credencial RADIUS de aparelho pertencente a outra conta.');
    $concurrencyBlocked=false;try{fs_subscriber_radius_reserve($pdo,$accountId,(int)$guest['id'],$partner,'guest-request',$pdo);}catch(RuntimeException $e){$concurrencyBlocked=str_contains($e->getMessage(),'simultâneas');}subscriber_domain_expect($concurrencyBlocked,'Limite agregado de simultaneidade não foi aplicado.');
    $pdo->prepare('UPDATE subscriber_access_grants SET activated_at=DATE_SUB(NOW(),INTERVAL 5 MINUTE) WHERE id=?')->execute([(int)$grant['grant']['id']]);$notConfirmed=fs_subscriber_radius_reconcile_account($pdo,$accountId,$pdo);$st=$pdo->prepare('SELECT status,failure_code FROM subscriber_access_grants WHERE id=?');$st->execute([(int)$grant['grant']['id']]);$failedGrant=$st->fetch();subscriber_domain_expect((int)$notConfirmed['failed']===1&&$failedGrant['status']==='failed'&&$failedGrant['failure_code']==='MIKROTIK_LOGIN_NOT_CONFIRMED','Login não confirmado pelo accounting não foi diagnosticado.');
    $grant=fs_subscriber_radius_reserve($pdo,$accountId,(int)$primary['id'],$partner,'after-unconfirmed',$pdo);subscriber_domain_expect($grant['grant']['status']==='active','Nova tentativa não foi liberada após login não confirmado.');
    $plan=['source'=>'global','id'=>1,'name'=>'Compra autenticada transacional','price_cents'=>500,'duration_minutes'=>60,'download_kbps'=>1000,'upload_kbps'=>500];
    $order=fs_guest_create_order($pdo,$partner,$plan,['mac'=>'02:00:00:AA:10:01','ip'=>'10.250.0.10'],null,['subscriber_account_id'=>$accountId,'subscriber_device_id'=>(int)$primary['id']]);$st=$pdo->prepare('SELECT subscriber_account_id,subscriber_device_id FROM guest_orders WHERE id=?');$st->execute([(int)$order['id']]);$linked=$st->fetch();subscriber_domain_expect((int)$linked['subscriber_account_id']===$accountId&&(int)$linked['subscriber_device_id']===(int)$primary['id'],'Compra consentida não foi vinculada à conta e aparelho.');
    $pdo->prepare("UPDATE guest_orders SET status='paid' WHERE id=?")->execute([(int)$order['id']]);$paidGrant=fs_guest_grant_access($pdo,(int)$order['id']);$rate->execute([$paidGrant['radius_username']]);subscriber_domain_expect((string)$rate->fetchColumn()==='500k/1000k','O acesso pago não respeitou a ordem upload/download exigida pelo RouterOS.');
    $pdo->prepare("UPDATE radreply SET value='1000k/500k' WHERE username=? AND attribute='Mikrotik-Rate-Limit'")->execute([$paidGrant['radius_username']]);fs_guest_grant_access($pdo,(int)$order['id']);$rate->execute([$paidGrant['radius_username']]);subscriber_domain_expect((string)$rate->fetchColumn()==='500k/1000k','A reconexão paga não corrigiu o limite de velocidade existente.');
    $pdo->prepare("UPDATE subscriber_accounts SET status='suspended' WHERE id=?")->execute([$accountId]);$pdo->prepare("UPDATE subscriber_entitlements SET status='suspended' WHERE account_id=?")->execute([$accountId]);$reconciled=fs_subscriber_radius_reconcile_account($pdo,$accountId,$pdo);subscriber_domain_expect((int)$reconciled['ended']===1,'Suspensão não encerrou a concessão ativa.');$st=$pdo->prepare('SELECT COUNT(*) FROM radcheck WHERE username=?');$st->execute([$grant['username']]);subscriber_domain_expect((int)$st->fetchColumn()===0,'Suspensão preservou a credencial técnica no RADIUS.');
    fs_subscriber_reconcile_devices($pdo,$accountId,false,2);$primarySuspended=fs_subscriber_device_by_id($pdo,(int)$primary['id']);subscriber_domain_expect($primarySuspended['status']==='suspended','Suspensão contratual não bloqueou os aparelhos.');
    $pdo->rollBack();unset($_COOKIE[fs_subscriber_device_cookie_name()]);
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();unset($_COOKIE[fs_subscriber_device_cookie_name()]);throw$e;}
echo "OK: {$checks} verificações integradas de conta, convite, RADIUS e compra.\n";
