CREATE TABLE IF NOT EXISTS courtesy_policy_defaults (
  id TINYINT UNSIGNED NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  grant_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 20,
  credit_validity_minutes INT UNSIGNED NOT NULL DEFAULT 1440,
  consumption_mode ENUM('online','elapsed') NOT NULL DEFAULT 'online',
  auth_mode ENUM('anonymous','account','account_device') NOT NULL DEFAULT 'account_device',
  requires_ad TINYINT(1) NOT NULL DEFAULT 0,
  exclude_active_paid TINYINT(1) NOT NULL DEFAULT 1,
  exclude_provider TINYINT(1) NOT NULL DEFAULT 1,
  enforcement_method ENUM('radius','mikrotik_local') NOT NULL DEFAULT 'radius',
  block_while_active TINYINT(1) NOT NULL DEFAULT 1,
  device_max_grants SMALLINT UNSIGNED DEFAULT 1,
  device_period_minutes INT UNSIGNED DEFAULT 1440,
  account_max_grants SMALLINT UNSIGNED DEFAULT NULL,
  account_period_minutes INT UNSIGNED DEFAULT NULL,
  partner_max_grants INT UNSIGNED DEFAULT NULL,
  partner_period_minutes INT UNSIGNED DEFAULT NULL,
  cooldown_after_end_minutes INT UNSIGNED NOT NULL DEFAULT 0,
  campaign_max_grants INT UNSIGNED DEFAULT NULL,
  campaign_starts_at DATETIME DEFAULT NULL,
  campaign_ends_at DATETIME DEFAULT NULL,
  reservation_ttl_seconds SMALLINT UNSIGNED NOT NULL DEFAULT 120,
  radius_group VARCHAR(64) DEFAULT NULL,
  revision INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO courtesy_policy_defaults (id) VALUES (1);

CREATE TABLE IF NOT EXISTS courtesy_partner_policies (
  partner_id INT(11) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  grant_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 20,
  credit_validity_minutes INT UNSIGNED NOT NULL DEFAULT 1440,
  consumption_mode ENUM('online','elapsed') NOT NULL DEFAULT 'online',
  auth_mode ENUM('anonymous','account','account_device') NOT NULL DEFAULT 'account_device',
  requires_ad TINYINT(1) NOT NULL DEFAULT 0,
  exclude_active_paid TINYINT(1) NOT NULL DEFAULT 1,
  exclude_provider TINYINT(1) NOT NULL DEFAULT 1,
  enforcement_method ENUM('radius','mikrotik_local') NOT NULL DEFAULT 'radius',
  block_while_active TINYINT(1) NOT NULL DEFAULT 1,
  device_max_grants SMALLINT UNSIGNED DEFAULT 1,
  device_period_minutes INT UNSIGNED DEFAULT 1440,
  account_max_grants SMALLINT UNSIGNED DEFAULT NULL,
  account_period_minutes INT UNSIGNED DEFAULT NULL,
  partner_max_grants INT UNSIGNED DEFAULT NULL,
  partner_period_minutes INT UNSIGNED DEFAULT NULL,
  cooldown_after_end_minutes INT UNSIGNED NOT NULL DEFAULT 0,
  campaign_max_grants INT UNSIGNED DEFAULT NULL,
  campaign_starts_at DATETIME DEFAULT NULL,
  campaign_ends_at DATETIME DEFAULT NULL,
  reservation_ttl_seconds SMALLINT UNSIGNED NOT NULL DEFAULT 120,
  radius_group VARCHAR(64) DEFAULT NULL,
  revision INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (partner_id),
  CONSTRAINT fk_courtesy_partner_policy_partner
    FOREIGN KEY (partner_id) REFERENCES partners (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO courtesy_partner_policies
  (partner_id,enabled,grant_minutes,credit_validity_minutes,consumption_mode,auth_mode,requires_ad,
   exclude_active_paid,exclude_provider,enforcement_method,block_while_active,
   device_max_grants,device_period_minutes,cooldown_after_end_minutes,
   reservation_ttl_seconds,revision)
SELECT id,
       1,
       LEAST(1440,GREATEST(1,free_minutes)),
       1440,
       'online',
       IF(require_auth=1,'account_device','anonymous'),
       0,
       1,
       1,
       'radius',
       1,
       GREATEST(1,max_uses_per_device),
       GREATEST(1,window_per_device_minutes),
       0,
       120,
       1
  FROM partners;

CREATE TABLE IF NOT EXISTS courtesy_grants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  idempotency_key_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  partner_id INT(11) DEFAULT NULL,
  partner_code VARCHAR(32) NOT NULL,
  partner_name VARCHAR(150) NOT NULL,
  policy_revision VARCHAR(32) NOT NULL,
  policy_snapshot LONGTEXT NOT NULL,
  device_key_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  account_key_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  device_mac VARCHAR(64) DEFAULT NULL,
  device_ip VARCHAR(45) DEFAULT NULL,
  account_username VARCHAR(64) DEFAULT NULL,
  portal VARCHAR(32) NOT NULL,
  source VARCHAR(32) NOT NULL,
  enforcement_method ENUM('radius','mikrotik_local') NOT NULL,
  consumption_mode ENUM('online','elapsed') NOT NULL,
  grant_minutes SMALLINT UNSIGNED NOT NULL,
  granted_seconds INT UNSIGNED NOT NULL,
  consumed_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('reserved','provisioning','active','exhausted','expired','revoked','failed') NOT NULL DEFAULT 'reserved',
  reservation_expires_at DATETIME NOT NULL,
  activated_at DATETIME DEFAULT NULL,
  expires_at DATETIME DEFAULT NULL,
  ended_at DATETIME DEFAULT NULL,
  ad_completed TINYINT(1) NOT NULL DEFAULT 0,
  radius_username VARCHAR(64) DEFAULT NULL,
  enforcement_ref VARCHAR(128) DEFAULT NULL,
  failure_code VARCHAR(64) DEFAULT NULL,
  failure_detail VARCHAR(255) DEFAULT NULL,
  legacy_source VARCHAR(32) DEFAULT NULL,
  legacy_id BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_courtesy_grants_public_id (public_id),
  UNIQUE KEY uq_courtesy_grants_idempotency (idempotency_key_hash),
  UNIQUE KEY uq_courtesy_grants_legacy (legacy_source,legacy_id),
  KEY idx_courtesy_grants_device (partner_id,device_key_hash,created_at),
  KEY idx_courtesy_grants_account (partner_id,account_key_hash,created_at),
  KEY idx_courtesy_grants_partner (partner_id,created_at),
  KEY idx_courtesy_grants_status (status,reservation_expires_at,expires_at),
  KEY idx_courtesy_grants_radius (radius_username),
  CONSTRAINT fk_courtesy_grants_partner
    FOREIGN KEY (partner_id) REFERENCES partners (id)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
