<?php
require_once __DIR__ . '/_boot.php';
$pdo=host_db();$token=trim((string)($_GET['token']??$_POST['token']??''));$invitation=partner_admin_invitation($pdo,$token);$error='';$done=false;
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!csrf_check($_POST['csrf']??''))$error='Sessão expirada. Recarregue a página.';
  elseif((string)($_POST['password']??'')!==(string)($_POST['password2']??''))$error='As senhas não coincidem.';
  else try{partner_admin_accept_invitation($pdo,$token,(string)($_POST['name']??''),(string)($_POST['password']??''));$done=true;$invitation=null;}catch(Throwable $e){$error=partner_admin_public_error($e);}
}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Convite FireSpot</title><link rel="stylesheet" href="/portal/assets/css/portal.css"><link rel="stylesheet" href="<?=host_h(host_admin_asset_url('host-admin.css'))?>"></head><body class="host-auth"><main class="container"><section class="card host-auth-card"><h2>Convite para administrar o estabelecimento</h2><?php if($done):?><div class="notice">Convite aceito. <a href="<?=host_h(host_admin_url('login'))?>">Entre no painel</a>.</div><?php elseif(!$invitation):?><div class="notice">Convite inválido, expirado ou revogado.</div><?php else:?><p>Você foi convidado para <strong><?=host_h($invitation['partner_name'])?></strong> como <?=host_h(partner_admin_roles()[$invitation['role']]??$invitation['role'])?>.</p><?php if($error):?><div class="notice error"><?=host_h($error)?></div><?php endif;?><form method="post" class="host-auth-form"><input type="hidden" name="csrf" value="<?=host_h(csrf_token())?>"><input type="hidden" name="token" value="<?=host_h($token)?>"><?php if(empty($invitation['existing_user_id'])):?><label>Nome<input name="name" required></label><label>Senha<input type="password" name="password" minlength="12" required></label><label>Confirmar senha<input type="password" name="password2" minlength="12" required></label><?php else:?><p class="notice">Sua identidade já existe. O aceite adicionará somente este novo vínculo.</p><input type="hidden" name="password"><input type="hidden" name="password2"><?php endif;?><button class="btn primary" type="submit">Aceitar convite</button></form><?php endif;?></section></main></body></html>
