<?php

declare(strict_types=1);

require_once __DIR__.'/../app/admin_auth.php';
admin_require_page();
require_once __DIR__.'/../app/db.php';
require_once __DIR__.'/../app/subscriber_admin.php';
require_once __DIR__.'/../app/hubsoft_cache.php';
require_once __DIR__.'/../app/payment_wallets.php';
require_once __DIR__.'/../app/control_center_integrations.php';
require_once __DIR__.'/../app/settings.php';
require_once __DIR__.'/../app/adsense.php';
require_once __DIR__.'/../app/public_url.php';
require_once __DIR__.'/../app/lib/promo_api.php';
require_once __DIR__.'/components/status-pill.php';

$pdo=db();
$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);
$section=(string)($_GET['section']??'overview');
if(!in_array($section,['overview','hubsoft','payments','messaging','adsense'],true))$section='overview';
$flash=$_SESSION['integrations_flash']??null;
unset($_SESSION['integrations_flash']);
$hubsoft=fs_subscriber_admin_hubsoft_status($pdo);
$hubsoftIntegration=(array)($hubsoft['integration']??[]);
$hubsoftCapability=fs_hubsoft_capability_status($pdo);
$hubsoftReady=!empty($hubsoft['configured'])&&!empty($hubsoft['crypto_ready'])&&!empty($hubsoftCapability['ok']);
$hubsoftCache=hubsoft_cache_status();
$hubsoftCacheSummary=(array)($hubsoftCache['summary']??[]);
$globalWallet=fs_control_center_global_wallet($pdo,false);
$walletStatus=fs_control_center_global_wallet_status($pdo);
$walletConfigured=!empty($walletStatus['configured']);
$messagingBase=promo_api_normalize_base(settings_get('promo_api_base',env('PROMO_API_BASE','')))?:'';
$messagingUser=(string)settings_get('promo_api_user',env('PROMO_API_USER',''));
$messagingTokenReady=trim((string)settings_get('promo_api_hash',env('PROMO_API_HASH','')))!=='';
$messagingEnabled=filter_var(settings_get('promo_enabled',env('PROMO_ENABLED','0')),FILTER_VALIDATE_BOOLEAN);
$messagingReady=$messagingEnabled&&$messagingBase!==''&&trim($messagingUser)!==''&&$messagingTokenReady;
$adsenseClient=(string)settings_get('adsense_client',env('ADSENSE_CLIENT',''));
$adsensePortal=(string)settings_get('adsense_slot_portal',env('ADSENSE_SLOT_PORTAL',''));
$adsenseVideo=(string)settings_get('adsense_slot_video',env('ADSENSE_SLOT_VIDEO',''));
$adsenseEnabled=filter_var(settings_get('adsense_enabled',env('ADSENSE_ENABLED','0')),FILTER_VALIDATE_BOOLEAN);
$adsenseReady=$adsenseEnabled&&$adsenseClient!=='';
$paymentTest=fs_control_center_integration_test_status($pdo,'mercadopago');
$messagingTest=fs_control_center_integration_test_status($pdo,'messaging');
$adsenseTest=fs_control_center_integration_test_status($pdo,'adsense');
if($paymentTest['last_test_ok']===null&&!empty($walletStatus['last_test_at']))$paymentTest=['last_test_at'=>$walletStatus['last_test_at'],'last_test_ok'=>true,'last_test_code'=>'WALLET_VALIDATED'];
$walletReady=$walletConfigured&&$paymentTest['last_test_ok']===true;
$canManage=admin_has_capability('system.integrations.manage');
$csrf=csrf_token();
$dateLabel=static function(mixed $value):string{$timestamp=strtotime((string)$value);return$timestamp?date('d/m/Y H:i',$timestamp):'Não registrado';};
$testResult=static function(array $state):string{if(($state['last_test_ok']??null)===true)return'Aprovado';if(($state['last_test_ok']??null)===false)return'Falhou';return'Não executado';};
$testFailure=static function(array $state):string{return($state['last_test_ok']??null)===false?(string)($state['last_test_code']??'TEST_FAILED'):'Nenhuma registrada';};
$titulo='Integrações';
$pageId='integracoes';
ob_start();
?>
<?php if($flash):?><div class="notice <?=!empty($flash['ok'])?'success':'error'?>"><?=htmlspecialchars((string)$flash['message'])?></div><?php endif;?>
<section class="fs-cc-toolbar"><div><span class="fs-cc-eyebrow">Sistema</span><h2>Integrações externas</h2><p>Credenciais, conectividade e diagnósticos técnicos em um único domínio. Segredos armazenados nunca são preenchidos novamente nos formulários.</p></div></section>

<?php if($section==='overview'):?>
<section class="fs-cc-integration-grid">
  <article class="card"><header><div><span>Assinantes</span><h2>HubSoft</h2></div><?=fs_cc_status_pill($hubsoftReady?'Pronta':'Revisar',$hubsoftReady?'success':'warning')?></header><p>OAuth, consulta de clientes e cache auxiliar.</p><dl><div><dt>Configuração</dt><dd><?=!empty($hubsoft['credentials_ready'])?'Credenciais armazenadas':'Credenciais pendentes'?></dd></div><div><dt>Dependências</dt><dd>HTTPS, OAuth e consulta pública</dd></div><div><dt>Último teste</dt><dd><?=$dateLabel($hubsoftIntegration['last_test_at']??null)?> · <?=!empty($hubsoftIntegration['last_test_ok'])?'Aprovado':(isset($hubsoftIntegration['last_test_ok'])?'Falhou':'Não executado')?></dd></div><div><dt>Última falha</dt><dd><?=isset($hubsoftIntegration['last_test_ok'])&&!$hubsoftIntegration['last_test_ok']?htmlspecialchars((string)($hubsoftIntegration['last_test_code']??'HUBSOFT_TEST_FAILED')):'Nenhuma registrada'?></dd></div></dl><a class="btn" href="?section=hubsoft">Configurar e testar</a></article>
  <article class="card"><header><div><span>Pagamentos</span><h2>Mercado Pago</h2></div><?=fs_cc_status_pill($walletReady?'Pronta':($walletConfigured?'Testar':'Pendente'),$walletReady?'success':'warning')?></header><p>Carteira global, webhook e Marketplace.</p><dl><div><dt>Configuração</dt><dd><?=$walletConfigured?'Carteira completa':'Carteira incompleta'?> · <?=htmlspecialchars($walletStatus['source'])?></dd></div><div><dt>Dependências</dt><dd>Public Key, Access Token e assinatura do webhook</dd></div><div><dt>Último teste</dt><dd><?=$dateLabel($paymentTest['last_test_at']??$walletStatus['last_test_at'])?> · <?=$testResult($paymentTest)?></dd></div><div><dt>Última falha</dt><dd><?=htmlspecialchars($testFailure($paymentTest))?></dd></div></dl><a class="btn" href="?section=payments">Ver e testar integração</a></article>
  <article class="card"><header><div><span>Comunicação</span><h2>Mensageria</h2></div><?=fs_cc_status_pill($messagingReady?'Pronta':'Pendente',$messagingReady?'success':'warning')?></header><p>PlaySMS/MeuJames para OTP e ofertas consentidas.</p><dl><div><dt>Configuração</dt><dd><?=$messagingEnabled?'Canal ativo':'Canal inativo'?> · <?=$messagingTokenReady?'token armazenado':'token pendente'?></dd></div><div><dt>Dependências</dt><dd>HTTPS, usuário, token e destino de teste</dd></div><div><dt>Último teste</dt><dd><?=$dateLabel($messagingTest['last_test_at'])?> · <?=$testResult($messagingTest)?></dd></div><div><dt>Última falha</dt><dd><?=htmlspecialchars($testFailure($messagingTest))?></dd></div></dl><a class="btn" href="?section=messaging">Configurar e testar</a></article>
  <article class="card"><header><div><span>Publicidade</span><h2>Google AdSense</h2></div><?=fs_cc_status_pill($adsenseReady?'Pronta':'Pendente',$adsenseReady?'success':'neutral')?></header><p>Cliente e slots globais para conteúdo publicitário.</p><dl><div><dt>Configuração</dt><dd><?=$adsenseEnabled?'Veiculação habilitada':'Veiculação desabilitada'?></dd></div><div><dt>Dependências</dt><dd>Client ID e slots numéricos</dd></div><div><dt>Última validação</dt><dd><?=$dateLabel($adsenseTest['last_test_at'])?> · <?=$testResult($adsenseTest)?></dd></div><div><dt>Última falha</dt><dd><?=htmlspecialchars($testFailure($adsenseTest))?></dd></div></dl><a class="btn" href="?section=adsense">Configurar e validar</a></article>
</section>

<?php elseif($section==='hubsoft'):?>
<section class="card"><header class="fs-cc-section-heading"><div><span class="fs-cc-eyebrow">HubSoft</span><h2>OAuth e consulta pública de clientes</h2><p>A integração técnica fica aqui; mapeamentos, rollout e atendimento permanecem em Assinantes FIRENETWORK.</p></div><?=fs_cc_status_pill($hubsoftReady?'Pronta':'Revisar',$hubsoftReady?'success':'warning')?></header><div class="fs-cc-kpis"><article class="card"><span>Credenciais</span><strong><?=!empty($hubsoft['credentials_ready'])?'OK':'Pendente'?></strong><small>criptografadas</small></article><article class="card"><span>Proteção</span><strong><?=!empty($hubsoft['crypto_ready'])?'OK':'Pendente'?></strong><small>chave interna</small></article><article class="card"><span>Consulta</span><strong><?=!empty($hubsoftCapability['ok'])?'OK':'Pendente'?></strong><small><?=htmlspecialchars((string)($hubsoftCapability['code']??'não validada'))?></small></article><article class="card"><span>Último teste</span><strong><?=!empty($hubsoftIntegration['last_test_ok'])?'Aceito':(isset($hubsoftIntegration['last_test_ok'])?'Falhou':'—')?></strong><small><?=$dateLabel($hubsoftIntegration['last_test_at']??null)?><?=isset($hubsoftIntegration['last_test_ok'])&&!$hubsoftIntegration['last_test_ok']?' · '.htmlspecialchars((string)($hubsoftIntegration['last_test_code']??'HUBSOFT_TEST_FAILED')):''?></small></article></div>
<?php if($canManage):?><?php if(!empty($hubsoftIntegration['requires_full_credentials'])):?><div class="notice error"><strong>Recuperação necessária:</strong> informe novamente usuário técnico, Client Secret e senha; os valores anteriores serão substituídos juntos.</div><?php endif;?><form method="post" action="actions/integration.php" class="fs-cc-form" autocomplete="off"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="return_section" value="hubsoft"><input type="hidden" name="action" value="hubsoft_credentials_save"><div class="fs-cc-form-grid"><label class="fs-cc-span-two"><span>URL da API</span><input type="url" name="base_url" maxlength="300" value="<?=htmlspecialchars((string)($hubsoftIntegration['base_url']??''))?>" required></label><label><span>Client ID</span><input name="client_id" maxlength="120" value="<?=htmlspecialchars((string)($hubsoftIntegration['client_id']??''))?>" required></label><label><span>Usuário técnico</span><input name="username" maxlength="190" autocomplete="off" <?=!empty($hubsoftIntegration['requires_full_credentials'])?'required':''?> placeholder="<?=!empty($hubsoftIntegration['has_username'])?'Armazenado — deixe vazio para manter':'Informe o usuário'?>"></label><label><span>Client Secret</span><input type="password" name="client_secret" autocomplete="new-password" <?=!empty($hubsoftIntegration['requires_full_credentials'])?'required':''?> placeholder="Armazenado — deixe vazio para manter"></label><label><span>Senha técnica</span><input type="password" name="password" autocomplete="new-password" <?=!empty($hubsoftIntegration['requires_full_credentials'])?'required':''?> placeholder="Armazenada — deixe vazio para manter"></label><label class="fs-cc-check"><input type="checkbox" name="active" value="1" <?=!array_key_exists('active',$hubsoftIntegration)||!empty($hubsoftIntegration['active'])?'checked':''?>><span>Integração ativa</span></label></div><div class="fs-cc-form-actions"><button class="btn primary" type="submit">Salvar integração</button></div></form><form method="post" action="actions/integration.php" class="fs-cc-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="return_section" value="hubsoft"><input type="hidden" name="action" value="hubsoft_connection_test"><button class="btn" type="submit" <?=!empty($hubsoft['configured'])?'':'disabled'?>>Testar OAuth e consulta</button></form><?php endif;?></section>
<section class="card"><header class="fs-cc-section-heading"><div><span class="fs-cc-eyebrow">Compatibilidade</span><h2>Cache auxiliar do cadastro legado</h2><p>Opcional; não controla Minha Conta nem o benefício atual.</p></div></header><?php if($canManage):?><form method="post" action="actions/integration.php" class="fs-cc-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="return_section" value="hubsoft"><input type="hidden" name="action" value="hubsoft_cache_settings_save"><label><span>Execuções automáticas por dia</span><input type="number" name="runs_per_day" min="0" max="24" value="<?=(int)$hubsoftCache['runs_per_day']?>" required><small>Use zero para desativar.</small></label><div class="fs-cc-form-actions"><button class="btn primary" type="submit">Salvar frequência</button><button class="btn" type="button" id="hubsoft-cache-run" <?=!empty($hubsoft['configured'])?'':'disabled'?>>Executar agora</button><span id="hubsoft-cache-run-status" aria-live="polite"></span></div></form><?php endif;?><dl class="fs-cc-fact-list"><div><dt>Automáticas hoje</dt><dd id="hubsoft-cache-automatic-today"><?=(int)$hubsoftCache['automatic_runs_today']?></dd></div><div><dt>Manuais hoje</dt><dd id="hubsoft-cache-manual-today"><?=(int)$hubsoftCache['manual_runs_today']?></dd></div><div><dt>Última execução</dt><dd id="hubsoft-cache-last-run"><?=htmlspecialchars((string)$hubsoftCache['last_run_label'])?></dd></div><div><dt>Resultado</dt><dd id="hubsoft-cache-summary"><?=!empty($hubsoftCacheSummary['timestamp_label'])?(int)$hubsoftCacheSummary['processed'].' processados · '.(int)$hubsoftCacheSummary['updated'].' atualizados':'Ainda não executada'?></dd></div></dl><div id="hubsoft-cache-errors" <?=!empty($hubsoftCacheSummary['errors'])?'':'hidden'?>><strong>Ocorrências sanitizadas</strong><div id="hubsoft-cache-error-list"><?php foreach((array)($hubsoftCacheSummary['errors']??[]) as $cacheError):?><p><?=htmlspecialchars((string)$cacheError)?></p><?php endforeach;?></div></div></section>

<?php elseif($section==='payments'):?>
<section class="fs-cc-integration-grid"><article class="card"><header><div><span>Credencial</span><h2>Carteira global</h2></div><?=fs_cc_status_pill($walletConfigured?'Configurada':'Pendente',$walletConfigured?'success':'warning')?></header><dl><div><dt>Origem</dt><dd><?=htmlspecialchars($walletStatus['source'])?></dd></div><div><dt>Ambiente</dt><dd><?=htmlspecialchars((string)($globalWallet['environment']??'—'))?></dd></div><div><dt>Token</dt><dd><?=htmlspecialchars((string)($globalWallet['credential_hint']??'não configurado'))?></dd></div><div><dt>Webhook</dt><dd><?=htmlspecialchars((string)($globalWallet['webhook_secret_hint']??'pendente'))?></dd></div></dl><a class="btn" href="recebimentos.php?section=wallets">Administrar carteira</a></article><article class="card"><header><div><span>Webhook</span><h2>Notificação de pagamentos</h2></div><?=fs_cc_status_pill(!empty($walletStatus['webhook_ready'])?'Configurada':'Revisar',!empty($walletStatus['webhook_ready'])?'success':'warning')?></header><p>URL canônica:</p><code><?=htmlspecialchars(rtrim(fs_public_base_url($pdo),'/').'/portal-v3/api/webhook.php')?></code><p>O segredo não é exibido.</p></article><article class="card"><header><div><span>Marketplace</span><h2>Contas recebedoras</h2></div></header><p>OAuth e repasses são objetos financeiros.</p><a class="btn" href="monetizacao.php?section=marketplace">Abrir no Financeiro</a></article><article class="card"><header><div><span>Política</span><h2>Checkout Pix</h2></div></header><p>Habilitação, expiração e texto global do checkout.</p><a class="btn" href="financeiro.php?section=settings">Configurar no Financeiro</a></article></section>
<section class="card fs-cc-separated-card"><header class="fs-cc-section-heading"><div><span class="fs-cc-eyebrow">Diagnóstico explícito</span><h2>Teste da carteira e do webhook</h2><p>Valida as capacidades do Access Token no provedor e executa localmente uma assinatura de webhook. Nenhum pagamento é criado.</p></div><?=fs_cc_status_pill($testResult($paymentTest),$paymentTest['last_test_ok']===true?'success':($paymentTest['last_test_ok']===false?'danger':'neutral'))?></header><dl class="fs-cc-fact-list"><div><dt>Última execução</dt><dd><?=$dateLabel($paymentTest['last_test_at'])?></dd></div><div><dt>Última falha sanitizada</dt><dd><?=htmlspecialchars($testFailure($paymentTest))?></dd></div><div><dt>Dependências</dt><dd>Carteira global ativa, Access Token, Public Key e assinatura do webhook</dd></div></dl><?php if($canManage):?><form method="post" action="actions/integration.php" class="fs-cc-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="return_section" value="payments"><input type="hidden" name="action" value="payments_connection_test"><button class="btn" type="submit" <?=$walletConfigured?'':'disabled'?>>Testar Mercado Pago e webhook</button></form><?php endif;?></section>

<?php elseif($section==='messaging'):?>
<section class="card"><header class="fs-cc-section-heading"><div><span class="fs-cc-eyebrow">PlaySMS / MeuJames</span><h2>Mensageria transacional e promocional</h2><p>Usada em OTP e ofertas consentidas. O token permanece vazio durante edição.</p></div><?=fs_cc_status_pill($messagingReady?'Pronta':'Pendente',$messagingReady?'success':'warning')?></header><?php if($canManage):?><form method="post" action="actions/integration.php" class="fs-cc-form" autocomplete="off"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="return_section" value="messaging"><input type="hidden" name="action" value="messaging_save"><div class="fs-cc-form-grid"><label class="fs-cc-span-two"><span>API base HTTPS</span><input type="url" name="promo_api_base" value="<?=htmlspecialchars($messagingBase)?>" required><small>Sem parâmetros ou credenciais na URL.</small></label><label><span>Usuário técnico</span><input name="promo_api_user" value="<?=htmlspecialchars($messagingUser)?>" required></label><label><span>Novo token</span><input type="password" name="promo_api_hash" autocomplete="new-password" placeholder="<?=$messagingTokenReady?'Armazenado — deixe vazio para manter':'Informe o token'?>"></label><label class="fs-cc-check"><input type="checkbox" name="promo_enabled" value="1" <?=$messagingEnabled?'checked':''?>><span>Integração ativa</span></label></div><div class="fs-cc-form-actions"><button class="btn primary" type="submit">Salvar mensageria</button></div></form><details class="fs-cc-editor"><summary>Executar teste explícito</summary><form method="post" action="actions/integration.php" class="fs-cc-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="return_section" value="messaging"><input type="hidden" name="action" value="messaging_test"><div class="fs-cc-form-grid"><label><span>Destino internacional</span><input name="promo_test_to" placeholder="+55DDDNUMERO" required></label><label class="fs-cc-span-two"><span>Mensagem</span><input name="promo_test_msg" maxlength="320" value="Teste FireSpot: OK" required></label></div><button class="btn" type="submit">Enviar teste</button></form></details><?php endif;?></section>
<section class="card fs-cc-separated-card"><dl class="fs-cc-fact-list"><div><dt>Último teste</dt><dd><?=$dateLabel($messagingTest['last_test_at'])?> · <?=$testResult($messagingTest)?></dd></div><div><dt>Última falha sanitizada</dt><dd><?=htmlspecialchars($testFailure($messagingTest))?></dd></div><div><dt>Dependências</dt><dd>Endpoint HTTPS, usuário, token e destino informado somente no teste explícito</dd></div></dl></section>

<?php elseif($section==='adsense'):?>
<section class="card"><header class="fs-cc-section-heading"><div><span class="fs-cc-eyebrow">Google</span><h2>AdSense</h2><p>Identificadores do provedor externo. Tempo de cortesia e inventário próprio pertencem às configurações de Campanhas.</p></div><?=fs_cc_status_pill($adsenseReady?'Pronta':'Pendente',$adsenseReady?'success':'neutral')?></header><?php if($canManage):?><form method="post" action="actions/integration.php" class="fs-cc-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="return_section" value="adsense"><input type="hidden" name="action" value="adsense_save"><div class="fs-cc-form-grid"><label class="fs-cc-span-two"><span>Client ID</span><input name="adsense_client" value="<?=htmlspecialchars($adsenseClient)?>" placeholder="ca-pub-..."></label><label><span>Slot do portal</span><input name="adsense_slot_portal" value="<?=htmlspecialchars($adsensePortal)?>"></label><label><span>Slot da página de anúncio</span><input name="adsense_slot_video" value="<?=htmlspecialchars($adsenseVideo)?>"></label><label class="fs-cc-check"><input type="checkbox" name="adsense_enabled" value="1" <?=$adsenseEnabled?'checked':''?>><span>Veiculação habilitada</span></label></div><div class="fs-cc-form-actions"><button class="btn primary" type="submit">Salvar AdSense</button></div></form><?php endif;?></section>
<section class="card fs-cc-separated-card"><header class="fs-cc-section-heading"><div><span class="fs-cc-eyebrow">Validação local</span><h2>Identificadores do AdSense</h2><p>Confere o formato e as dependências declarativas sem simular impressão, clique ou receita.</p></div><?=fs_cc_status_pill($testResult($adsenseTest),$adsenseTest['last_test_ok']===true?'success':($adsenseTest['last_test_ok']===false?'danger':'neutral'))?></header><dl class="fs-cc-fact-list"><div><dt>Última validação</dt><dd><?=$dateLabel($adsenseTest['last_test_at'])?></dd></div><div><dt>Última falha sanitizada</dt><dd><?=htmlspecialchars($testFailure($adsenseTest))?></dd></div><div><dt>Dependências</dt><dd>Client ID no formato ca-pub e slots numéricos quando informados</dd></div></dl><?php if($canManage):?><form method="post" action="actions/integration.php" class="fs-cc-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="return_section" value="adsense"><input type="hidden" name="action" value="adsense_configuration_test"><button class="btn" type="submit" <?=$adsenseClient!==''?'':'disabled'?>>Validar configuração</button></form><?php endif;?></section>
<?php endif;?>
<?php
$conteudo=(string)ob_get_clean();
require __DIR__.'/layout.php';
