<?php
require_once __DIR__.'/_boot.php';
$pdo=conta_db();$accountFeature=fs_subscriber_feature_enabled($pdo,'subscriber_account_enabled',false);$inviteFeature=fs_subscriber_feature_enabled($pdo,'subscriber_invites_enabled',false);$requestedNext=(string)($_GET['next']??'');if($requestedNext!==''&&str_starts_with($requestedNext,'/portal-v3/')&&!str_contains($requestedNext,"\n")&&!str_contains($requestedNext,"\r"))$_SESSION['subscriber_after_login']=$requestedNext;$account=$accountFeature?fs_subscriber_current($pdo):null;$postAction='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{
        if(!$accountFeature)throw new RuntimeException('A Minha Conta ainda não foi liberada.');if(!csrf_check($_POST['csrf']??''))throw new RuntimeException('Sua sessão expirou. Recarregue a página.');$action=(string)($_POST['action']??'');$postAction=$action;
        if($action==='login_start'){$result=fs_subscriber_login_start($pdo,(string)($_POST['document']??''));$_SESSION['subscriber_login_challenge']=$result['challenge'];$_SESSION['subscriber_login_hint']=$result['contact_hint'];conta_redirect('/conta/verificar.php');}
        if($action==='login_password'){fs_subscriber_login_password($pdo,(string)($_POST['document']??''),(string)($_POST['password']??''),isset($_POST['remember']));$next=(string)($_SESSION['subscriber_after_login']??'/conta/');unset($_SESSION['subscriber_after_login']);if(!str_starts_with($next,'/portal-v3/'))$next='/conta/';conta_redirect($next);}
        if(!$account)$account=fs_subscriber_require($pdo);$accountId=(int)$account['id'];
        if($action==='invite_create'){$invite=fs_subscriber_invite_create($pdo,$accountId,$_POST);$base=fs_public_base_url($pdo);$invite['url']=$base.'/portal-v3/convite.php?token='.rawurlencode($invite['token']);$_SESSION['subscriber_invite_reveal']=$invite;conta_flash('success','Convite criado. O código e o QR são exibidos uma única vez.');}
        elseif($action==='invite_revoke'){fs_subscriber_invite_revoke($pdo,$accountId,(int)($_POST['invite_id']??0));conta_flash('success','Convite revogado e a vaga reservada foi liberada.');}
        elseif($action==='device_primary'){fs_subscriber_authorize_primary($pdo,$accountId);conta_flash('success','Este navegador foi autorizado como aparelho principal.');}
        elseif($action==='device_revoke'){fs_subscriber_device_revoke($pdo,$accountId,(int)($_POST['device_id']??0));conta_flash('success','Aparelho revogado. A vaga respeitará o período de segurança informado.');}
        elseif($action==='refresh'){$result=fs_subscriber_refresh_account($pdo,$accountId);if(empty($result['ok']))throw new RuntimeException((string)($result['message']??'Não foi possível atualizar o benefício.'));conta_flash('success','Benefício atualizado com a FIRENETWORK.');}
        elseif($action==='logout_all'){fs_subscriber_logout($pdo,true);conta_redirect('/conta/');}
        elseif(!in_array($action,['invite_create'],true))throw new RuntimeException('Ação inválida.');
        conta_redirect('/conta/');
    }catch(Throwable $e){conta_flash('error',conta_error($e));conta_redirect($postAction==='login_password'?'/conta/?method=password':'/conta/');}
}
$flash=conta_take_flash();$reveal=$_SESSION['subscriber_invite_reveal']??null;
conta_layout_start();
if(!$accountFeature):?>
<section class="account-card account-auth stack"><div><span class="account-eyebrow">Implantação controlada</span><h1>Minha Conta em preparação</h1><p>O benefício FIRENETWORK ainda não foi liberado para uso público.</p></div></section>
<?php elseif(!$account):?>
<?php $selectedMethod=(string)($_GET['method']??'otp');if(!in_array($selectedMethod,['otp','password'],true))$selectedMethod='otp';?>
<section class="account-card account-auth stack"><div><span class="account-eyebrow">Acesso exclusivo</span><h1>Minha Conta FIRENETWORK</h1><p>Consulte seu benefício FireSpot, autorize familiares e gerencie os aparelhos vinculados ao seu contrato.</p></div><?php if($flash):?><div class="notice <?=conta_h($flash['type'])?>"><?=conta_h($flash['message'])?></div><?php endif;?>
<div class="auth-method-tabs" role="tablist" aria-label="Forma de entrada"><button id="auth-tab-otp" type="button" role="tab" aria-controls="auth-panel-otp" data-auth-tab="otp" aria-selected="<?=$selectedMethod==='otp'?'true':'false'?>">Código por SMS</button><button id="auth-tab-password" type="button" role="tab" aria-controls="auth-panel-password" data-auth-tab="password" aria-selected="<?=$selectedMethod==='password'?'true':'false'?>">Senha do aplicativo</button></div>
<div id="auth-panel-otp" class="auth-method-panel" role="tabpanel" aria-labelledby="auth-tab-otp" data-auth-panel="otp" <?=$selectedMethod==='otp'?'':'hidden'?>>
  <form method="post" class="stack"><input type="hidden" name="csrf" value="<?=conta_h(csrf_token())?>"><input type="hidden" name="action" value="login_start"><label>CPF ou CNPJ do titular<input name="document" inputmode="numeric" autocomplete="username" maxlength="18" required></label><button class="primary" type="submit">Receber código de acesso</button></form><p class="subtle">Enviamos um código ao telefone confirmado no cadastro FIRENETWORK.</p>
</div>
<div id="auth-panel-password" class="auth-method-panel" role="tabpanel" aria-labelledby="auth-tab-password" data-auth-panel="password" <?=$selectedMethod==='password'?'':'hidden'?>>
  <form method="post" class="stack"><input type="hidden" name="csrf" value="<?=conta_h(csrf_token())?>"><input type="hidden" name="action" value="login_password"><label>CPF ou CNPJ do titular<input name="document" inputmode="numeric" autocomplete="username" maxlength="18" required></label><label>Senha do aplicativo FIRENETWORK<input name="password" type="password" autocomplete="current-password" maxlength="255" required></label><label class="account-check"><input type="checkbox" name="remember" value="1" checked><span>Lembrar este navegador por 30 dias</span></label><button class="primary" type="submit">Entrar com minha senha</button></form><p class="subtle">É a mesma senha da Central do Assinante ou do aplicativo. Ela é validada diretamente no HubSoft e nunca é salva no FireSpot.</p>
</div>
</section>
<script>document.querySelectorAll('[data-auth-tab]').forEach(tab=>tab.addEventListener('click',()=>{const method=tab.dataset.authTab;document.querySelectorAll('[data-auth-tab]').forEach(item=>item.setAttribute('aria-selected',item===tab?'true':'false'));document.querySelectorAll('[data-auth-panel]').forEach(panel=>panel.hidden=panel.dataset.authPanel!==method);const url=new URL(location.href);url.searchParams.set('method',method);history.replaceState(null,'',url);}));</script>
<?php else:$accountId=(int)$account['id'];$entitlement=fs_subscriber_entitlement($pdo,$accountId);$occupancy=fs_subscriber_device_occupancy($pdo,$accountId);$devices=fs_subscriber_devices($pdo,$accountId);$invites=$inviteFeature?fs_subscriber_invites($pdo,$accountId):[];$st=$pdo->prepare('SELECT o.plan_name,o.amount_cents,o.status,o.created_at,p.name partner_name FROM guest_orders o JOIN partners p ON p.id=o.partner_id WHERE o.subscriber_account_id=? ORDER BY o.id DESC LIMIT 30');$st->execute([$accountId]);$accountOrders=$st->fetchAll()?:[];$st=$pdo->prepare('SELECT g.status,g.failure_code,g.created_at,g.activated_at,g.ended_at,p.name partner_name,h.name hotspot_name FROM subscriber_access_grants g JOIN partners p ON p.id=g.partner_id JOIN partner_hotspots h ON h.id=g.hotspot_id WHERE g.account_id=? ORDER BY g.id DESC LIMIT 30');$st->execute([$accountId]);$accountGrants=$st->fetchAll()?:[];?>
<section class="account-card account-hero"><div><span class="account-eyebrow">Benefício FireSpot</span><h1><?=conta_h($account['display_name']?:'Cliente FIRENETWORK')?></h1><p>Seu contrato é a autoridade do benefício; cada aparelho recebe uma autorização própria.</p></div><div class="actions"><?php if(!empty($_SESSION['subscriber_after_login'])):?><a class="button primary" href="<?=conta_h((string)$_SESSION['subscriber_after_login'])?>">Voltar ao Portal V3</a><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=conta_h(csrf_token())?>"><input type="hidden" name="action" value="refresh"><button type="submit">Atualizar benefício</button></form><a class="button" href="/conta/sair.php">Sair</a></div></section>
<?php if($flash):?><div class="notice <?=conta_h($flash['type'])?>"><?=conta_h($flash['message'])?></div><?php endif;?>
<?php if($inviteFeature&&$reveal):?><section class="account-card invite-reveal"><img src="/conta/qr.php?invite=<?=conta_h($reveal['public_id'])?>" alt="QR Code do convite"><div><span class="account-eyebrow">Exibido uma única vez</span><h2>Convite criado</h2><p>Digite o código no Portal V3 ou leia o QR no aparelho convidado.</p><div class="invite-code"><?=conta_h($reveal['code'])?></div><p class="subtle">Expira em <?=conta_h(date('d/m/Y H:i',strtotime($reveal['expires_at'])))?>. O link é de uso único.</p><input value="<?=conta_h($reveal['url'])?>" readonly onclick="this.select()"></div></section><?php endif;?>
<section class="account-card stack"><div><span class="account-eyebrow">Situação atual</span><h2><?=conta_h($entitlement['profile_name']??'Benefício indisponível')?></h2></div><div class="account-benefit"><div><span>Situação</span><strong><?=fs_subscriber_entitlement_usable($entitlement)?'Ativo':'Revisar'?></strong></div><div><span>Aparelhos</span><strong><?=(int)$occupancy['used']?> / <?=(int)$occupancy['limit']?></strong></div><div><span>Vagas livres</span><strong><?=(int)$occupancy['available']?></strong></div><div><span>Simultâneos</span><strong><?=(int)($entitlement['concurrent_limit']??0)?></strong></div></div></section>
<div class="account-grid"><section class="account-card stack"><div><span class="account-eyebrow">Aparelhos</span><h2>Autorizações</h2></div><div class="table-wrap"><table><thead><tr><th>Aparelho</th><th>Validade</th><th>Situação</th><th></th></tr></thead><tbody><?php foreach($devices as $device):?><tr><td><strong><?=conta_h($device['label']?:($device['device_kind']==='primary'?'Meu aparelho':'Convidado'))?></strong><br><small><?=conta_h($device['device_kind']==='primary'?'Principal':'Convidado')?></small></td><td><?=conta_h($device['expires_at']?date('d/m/Y H:i',strtotime($device['expires_at'])):'Enquanto autorizado')?></td><td><span class="pill <?=$device['status']==='active'?'ok':'off'?>"><?=conta_h($device['status'])?></span></td><td><?php if($device['status']==='active'):?><form method="post"><input type="hidden" name="csrf" value="<?=conta_h(csrf_token())?>"><input type="hidden" name="action" value="device_revoke"><input type="hidden" name="device_id" value="<?=(int)$device['id']?>"><button class="danger" type="submit">Revogar</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$devices):?><tr><td colspan="4">Nenhum aparelho autorizado.</td></tr><?php endif;?></tbody></table></div><?php if($inviteFeature&&(int)$occupancy['available']>0&&!array_filter($devices,static fn(array $d):bool=>$d['device_kind']==='primary'&&$d['status']==='active')):?><form method="post"><input type="hidden" name="csrf" value="<?=conta_h(csrf_token())?>"><input type="hidden" name="action" value="device_primary"><button type="submit">Autorizar este navegador como principal</button></form><?php endif;?></section>
<?php if($inviteFeature):?><section class="account-card stack"><div><span class="account-eyebrow">Familiares</span><h2>Novo convite</h2><p>O convite é único e cria uma autorização própria no primeiro aparelho que o utilizar.</p></div><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=conta_h(csrf_token())?>"><input type="hidden" name="action" value="invite_create"><label>Apelido<input name="label" maxlength="120" placeholder="Ex.: Celular da Maria"></label><label>Validade da autorização<select name="authorization_mode"><option value="while_authorized">Enquanto eu autorizar</option><option value="temporary">Por um período</option><option value="until_date">Até uma data</option></select></label><label>Minutos, se temporário<input name="access_duration_minutes" type="number" min="15" max="43200" value="1440"></label><label>Data final, se escolhida<input name="authorization_until" type="datetime-local"></label><button class="primary" type="submit" <?=(int)$occupancy['available']<1?'disabled':''?>>Gerar convite de uso único</button></form></section><?php else:?><section class="account-card stack"><div><span class="account-eyebrow">Implantação controlada</span><h2>Convites ainda indisponíveis</h2><p>Seus aparelhos existentes continuam visíveis, mas novas autorizações serão liberadas em uma etapa posterior.</p></div></section><?php endif;?></div>
<?php if($inviteFeature):?><section class="account-card stack"><div><span class="account-eyebrow">Histórico recente</span><h2>Convites</h2></div><div class="table-wrap"><table><thead><tr><th>Apelido</th><th>Criado</th><th>Expira</th><th>Situação</th><th></th></tr></thead><tbody><?php foreach($invites as $invite):?><tr><td><?=conta_h($invite['label']?:'Convidado')?></td><td><?=conta_h(date('d/m/Y H:i',strtotime($invite['created_at'])))?></td><td><?=conta_h(date('d/m/Y H:i',strtotime($invite['expires_at'])))?></td><td><span class="pill <?=$invite['status']==='created'?'ok':'off'?>"><?=conta_h($invite['status'])?></span></td><td><?php if($invite['status']==='created'):?><form method="post"><input type="hidden" name="csrf" value="<?=conta_h(csrf_token())?>"><input type="hidden" name="action" value="invite_revoke"><input type="hidden" name="invite_id" value="<?=(int)$invite['id']?>"><button class="danger" type="submit">Revogar</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$invites):?><tr><td colspan="5">Nenhum convite gerado.</td></tr><?php endif;?></tbody></table></div></section><?php endif;?>
<div class="account-grid">
<section class="account-card stack"><div><span class="account-eyebrow">Histórico</span><h2>Acessos FIRENETWORK</h2></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Local</th><th>Situação</th></tr></thead><tbody><?php foreach($accountGrants as $grant):?><tr><td><?=conta_h(date('d/m/Y H:i',strtotime($grant['created_at'])))?></td><td><?=conta_h($grant['partner_name'].' · '.$grant['hotspot_name'])?></td><td><span class="pill <?=$grant['status']==='active'?'ok':'off'?>"><?=conta_h($grant['status'])?></span><?php if($grant['failure_code']):?><br><small><?=conta_h($grant['failure_code'])?></small><?php endif;?></td></tr><?php endforeach;?><?php if(!$accountGrants):?><tr><td colspan="3">Nenhum acesso incluído registrado.</td></tr><?php endif;?></tbody></table></div></section>
<section class="account-card stack"><div><span class="account-eyebrow">Consentimento explícito</span><h2>Compras vinculadas</h2><p>Somente compras que você escolheu vincular aparecem aqui.</p></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Local / plano</th><th>Valor</th><th>Situação</th></tr></thead><tbody><?php foreach($accountOrders as $order):?><tr><td><?=conta_h(date('d/m/Y H:i',strtotime($order['created_at'])))?></td><td><?=conta_h($order['partner_name'])?><br><small><?=conta_h($order['plan_name'])?></small></td><td>R$ <?=conta_h(number_format((int)$order['amount_cents']/100,2,',','.'))?></td><td><span class="pill <?=$order['status']==='paid'?'ok':'off'?>"><?=conta_h($order['status'])?></span></td></tr><?php endforeach;?><?php if(!$accountOrders):?><tr><td colspan="4">Nenhuma compra foi vinculada.</td></tr><?php endif;?></tbody></table></div></section>
</div>
<section class="account-card stack"><form method="post" class="actions"><input type="hidden" name="csrf" value="<?=conta_h(csrf_token())?>"><input type="hidden" name="action" value="logout_all"><button class="danger" type="submit">Encerrar todas as sessões da Minha Conta</button><span class="subtle">Revoga os navegadores lembrados; não remove aparelhos autorizados.</span></form><div class="actions"><a class="button danger" href="/conta/excluir.php">Excluir minha conta FireSpot</a><span class="subtle">Anonimiza os dados locais sem cancelar o contrato FIRENETWORK.</span></div></section>
<?php endif;conta_layout_end();
